const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.HTMLElement,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.SpeechSynthesis,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Touch.Cnds.OnHoldGestureObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.SpeechSynthesis.Acts.SpeakText,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.SpeechSynthesis.Exps.VoiceURIAt,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Browser.Acts.LockOrientation,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.ScriptsInEvents.Interface_es_Event1_Act1,
		C3.ScriptsInEvents.Interface_es_Event2_Act1,
		C3.ScriptsInEvents.Interface_es_Event3_Act1,
		C3.ScriptsInEvents.Interface_es_Event4_Act1,
		C3.ScriptsInEvents.Interface_es_Event5_Act1,
		C3.ScriptsInEvents.Interface_es_Event6_Act1,
		C3.ScriptsInEvents.Interface_es_Event7_Act1,
		C3.ScriptsInEvents.Interface_es_Event8_Act1,
		C3.ScriptsInEvents.Interface_es_Event9_Act1,
		C3.Plugins.SpeechSynthesis.Acts.StopSpeaking,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.lowercase,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.ScriptsInEvents.Levels_es_Event12_Act2,
		C3.ScriptsInEvents.Dailytask_es_Event6_Act1
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Browser: 0},
	{Audio: 0},
	{Mouse: 0},
	{Keyboard: 0},
	{HTMLElement: 0},
	{Tween: 0},
	{elimu_logo: 0},
	{Sine: 0},
	{play_btn: 0},
	{home_bg: 0},
	{back_btn: 0},
	{counter_container: 0},
	{count_instruction_txt: 0},
	{status_btn: 0},
	{level_txt: 0},
	{SpeechSynthesis: 0},
	{range_img: 0},
	{count_logo: 0},
	{count_instruction_img: 0},
	{coin_holder_img: 0},
	{coin_txt: 0},
	{countNumber: 0},
	{fruit_img: 0},
	{IsCounter: 0},
	{fruit_holder_img: 0},
	{Operation: 0},
	{fruit_counter_img: 0},
	{overlay: 0},
	{level: 0},
	{level_btn: 0},
	{home_bg2: 0},
	{select_level_txt: 0},
	{demo_upgrade: 0},
	{unlock_btn: 0},
	{explore_btn: 0},
	{fruit_splash_img: 0},
	{fruit_remover_img: 0},
	{fruit_adder_img: 0},
	{firework_splash_img: 0},
	{VolumeLevel: 0},
	{ToCount: 0},
	{IsCorrect: 0},
	{Counting: 0},
	{Counted: 0},
	{Coins: 0},
	{ObjectType: 0},
	{ObjectSpec: 0},
	{Location: 0},
	{ObjectName: 0},
	{Instructor: 0},
	{visibility: 0},
	{WaitingTimeMax: 0},
	{WaitingTime: 0},
	{UserEmail: 0},
	{GameAction: 0},
	{GameKey: 0},
	{UserFirstname: 0},
	{UserLastname: 0},
	{Username: 0},
	{AppId: 0},
	{dataKey: 0},
	{value: 0},
	{GameplayLayout: 0},
	{Level: 0},
	{CurrentLevel: 0},
	{LevelRound: 0},
	{LevelRoundLimit: 0},
	{Sequence: 0},
	{IsFullMode: 0},
	{DemoLimit: 0},
	{GameMode: 0},
	{DailyTaskCounter: 0},
	{DAILY_TASK_LIMIT: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	HTMLElement: class extends self.IHTMLElementInstance {},
	elimu_logo: class extends self.ISpriteInstance {},
	play_btn: class extends self.ISpriteInstance {},
	home_bg: class extends self.ISpriteInstance {},
	back_btn: class extends self.ISpriteInstance {},
	counter_container: class extends self.ISpriteInstance {},
	count_instruction_txt: class extends self.ITextInstance {},
	status_btn: class extends self.ISpriteInstance {},
	level_txt: class extends self.ITextInstance {},
	SpeechSynthesis: class extends self.IInstance {},
	range_img: class extends self.ISpriteInstance {},
	count_logo: class extends self.ISpriteInstance {},
	count_instruction_img: class extends self.ISpriteInstance {},
	coin_holder_img: class extends self.ISpriteInstance {},
	coin_txt: class extends self.ITextInstance {},
	fruit_img: class extends self.ISpriteInstance {},
	fruit_holder_img: class extends self.ISpriteInstance {},
	fruit_counter_img: class extends self.ISpriteInstance {},
	overlay: class extends self.ISpriteInstance {},
	level_btn: class extends self.ISpriteInstance {},
	home_bg2: class extends self.ISpriteInstance {},
	select_level_txt: class extends self.ITextInstance {},
	demo_upgrade: class extends self.ISpriteInstance {},
	unlock_btn: class extends self.ISpriteInstance {},
	explore_btn: class extends self.ISpriteInstance {},
	fruit_splash_img: class extends self.ISpriteInstance {},
	fruit_remover_img: class extends self.ISpriteInstance {},
	fruit_adder_img: class extends self.ISpriteInstance {},
	firework_splash_img: class extends self.ISpriteInstance {}
}